services:

  # The service interface which offers transformation entry points based on pygeopi processing standards
  mgdm2oereb-service:
    user: ${CURRENT_UID}:${CURRENT_GID}
    build:
      context: ./mgdm2oereb_service
      target: dev
      args:
        MGDM2OEREB_VERSION: 5d99c8c6c7bad4df6a9bd5e40013b05ceb88f28e
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PYGEOAPI_CONFIG
      - PYGEOAPI_OPENAPI
      - GUNICORN_CONFIG
      - MGDM2OEREB_TRAFO_CONFIG
      - ILIVALIDATOR_SERVICE=https://ilicheck.geo.sh.ch
      - MGDM2OEREB_DATA
      - FLASK_DEBUG=${MGDM2OEREB_SERVICE_FLASK_ENV}
    volumes:
      - data:${MGDM2OEREB_DATA}
      - ./mgdm2oereb_service:/app
    ports:
      - "5000:5000"
  rss-trigger:
    environment:
      - RSS_STORAGE_PATH
      - RSS_URL
      - GIT_REPO_PATH
      - GIT_REPO_URL
      - MAIL
    build:
      context: ./rss_trigger
      dockerfile: Dockerfile
    volumes:
      - rss-storeage:/rss-storeage
      - ./rss_trigger/:/app
      - ./.ssh:/root/.ssh
    restart: unless-stopped
volumes:
  data:
  rss-storeage:
