server:
    bind:
        host: 0.0.0.0
        port: 5000
    url: http://localhost:5000/oapi
    mimetype: application/json; charset=UTF-8
    encoding: utf-8
    gzip: false
    languages:
        # First language is the default language
        - en-US
        - de-CH
    # cors: true
    pretty_print: true
    limit: 10
    # templates:
      # path: /path/to/Jinja2/templates
      # static: /path/to/static/folder # css/js/img
    map:
        url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
        attribution: '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'
    manager:
        name: mgdm2oereb_service.pygeoapi_plugins.process_manager.tinydb.CustomTinyDBManager
        connection: /tmp/pygeoapi-process-manager.db
        output_dir: /tmp/
    # ogc_schemas_location: /opt/schemas.opengis.net

logging:
    level: DEBUG
    # level: ERROR
    #logfile: /tmp/pygeoapi.log

metadata:
    identification:
        title:
            en: MGDM2OEREB Service
            de: MGDM2OEREB Service
        description:
            en: MGDM2OEREB Service provides transformation processes from MGDMs to OeREBKRMtrsfr
            de: MGDM2OEREB Service bietet Zugriff auf die Transformationen von MGDMs zu OeREBKRMtrsfr
        keywords:
            en:
                - INTERLIS
                - OeREBKRMtrsfr
                - MGDM2OEREB
                - PLR
                - Cadastre of Public Law Restrictions
                - PLR Cadastre
            de:
                - INTERLIS
                - OeREBKRMtrsfr
                - MGDM2OEREB
                - ÖREB-Kataster
                - ÖREB
                - Kataster der öffentlich-rechtlichen Eigentumsbeschränkungen
        keywords_type: theme
        terms_of_service: https://creativecommons.org/licenses/by/4.0/
        url: https://example.org
    license:
        name: CC-BY 4.0 license
        url: https://creativecommons.org/licenses/by/4.0/
    provider:
        name: OPENGIS.ch
        url: https://www.opengis.ch/
    contact:
        name: Rudert, Clemens
        position:
        address: clemens@opengis.ch
        city: Laax
        stateorprovince: Graubünden
        postalcode: 7031
        country: Switzerland
        email: info@opengis.ch
        url: https://www.opengis.ch/
        hours: Mo-Fr 08:00-17:00
        instructions: During hours of service. Off on weekends.
        role: pointOfContact

resources:

    mgdm2oereb-oereblex:
        type: process
        processor:
            name: mgdm2oereb_service.pygeoapi_plugins.process.mgdm2oereb.processors.Mgdm2OerebTransformatorOereblex
    mgdm2oereb:
        type: process
        processor:
            name: mgdm2oereb_service.pygeoapi_plugins.process.mgdm2oereb.processors.Mgdm2OerebTransformator